### ISSUE TITLE
Production deployment

### ISSUE THREAD

**Issue by MandanaMoshref** [EnviDat/envidat_frontend#2]
How the dist folder should be deployed on the ckan production site?

**Comment by DomDomHaas** [comment]
Hi There

Thanks for your interest in the EnviDat frontend.

Yes, after building the project the content of the dist folder has to go on the root of your server.
We also had to change the proxy rules to make sure www.envidat.ch/ only serves this frontend and www.envidat.ch/dataset/ serves the original ckan frontend from the server side.

Because at this point (as of Version 0.8.x) this frontend is for non-logged in functionalities. Meaning basically only for browsing and download non-restricted resources. If a user wants to upload / edit / delete any dataset it has to be done via the ckan ui.

Signing is in development, first steps have been done in version 0.6.9x but it works with a custom extension for password-less sign in.

I've updated the readme in the master branch with more detailed instructions about the usage. Please let me know if that helps or you need further information.

**Comment by MandanaMoshref** [comment]
Many thanks for your explanation.
I believe the readMe is now very helpful and straightforward for working with the code.
I did some researches by myself and figured out somehow how to deploy the code on the production site so that similar to envidat.ch it only servers the frontend page but the rest resides on the original CKAN page/UI.

Thanks for the update and also for sharing the code.
I close the issue then.
